### Pandas Basic
Pandas is a wrapper of 2 languages:
- Numpy - numerical data and mathemetical operations
- Matplotlib - data visualization

In [72]:
import numpy as np
import pandas as pd

In [73]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

Pandas Datastructures
Series- single dimensional datastructure
DataFrame-multidimensional table

In [74]:
ser1 = pd.Series([10,20,30,40], index=["A","B","C","D"])
print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [75]:
ser1.loc["A"]

np.int64(10)

In [76]:
ser1.iloc[0]

np.int64(10)

In [77]:
#creating a series from a pre-exiting dictionary
d = {
    "a": 1,
    "b": 0,
    "c": 2,
    "d": 100    
}
print(d)

{'a': 1, 'b': 0, 'c': 2, 'd': 100}

In [78]:
pd.Series(d)

a      1
b      0
c      2
d    100
dtype: int64

In [79]:
ser2 = pd.Series(d)
print(ser2)

a      1
b      0
c      2
d    100
dtype: int64

In [80]:
d1 = {
    "a": 1.3,
    "b": 0.5,
    "c": 2.4    
}

ser3 = pd.Series(d1)
print(ser3)

a    1.3
b    0.5
c    2.4
dtype: float64

In [81]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}
ser4 = pd.Series(calories, index=['day1', 'day3'])
print(ser4)

day1     700
day3    1200
dtype: int64

In [82]:
ser5 = pd.Series(5.0, index=["a","b","c"])
print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

### Data Frame - Index and column

In [83]:
fruit_data = {
    'apple_sales': [3,2,3,5,7,0,2,2],
    'orange_sales': [3,2,5,5,8,0,2,2]
}
# idx = ['Day 1','Day 2','Day 3','Day 4','Day 5','Day 6','Day 7','Day 8']

idx = pd.RangeIndex(2000, 2008)
purchases = pd.DataFrame(fruit_data, index=[idx])
print(purchases)

      apple_sales  orange_sales
2000            3             3
2001            2             2
2002            3             5
2003            5             5
2004            7             8
2005            0             0
2006            2             2
2007            2             2

In [84]:
rows, cols = purchases.shape
print(f'Rows: {rows}')
print(f'Columns: {cols}')

Rows: 8
Columns: 2

In [85]:
purchases.head() #view first 5 elements

      apple_sales  orange_sales
2000            3             3
2001            2             2
2002            3             5
2003            5             5
2004            7             8

In [86]:
purchases.tail() # view bottom 5 elements

      apple_sales  orange_sales
2003            5             5
2004            7             8
2005            0             0
2006            2             2
2007            2             2

#### Importing Files with Pandas
.read_csv()
.read_excel()
.read_json()
.read_sql()

In [87]:
employee_df = pd.read_csv('data/employee.csv')
employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [88]:
rows, cols = employee_df.shape
print("Rows: ", rows)
print("Columns: ", cols)

Rows:  15
Columns:  4

In [89]:
employee_df.dtypes

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [99]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

In [100]:
student_df.head()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [101]:
student_df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [102]:
list_Index = student_df.columns
print('Columns Names', list_Index)

Columns Names Index(['Name', 'Age', 'Marks'], dtype='str')

In [104]:
cars_df = pd.read_json('data/cars.json')
cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [91]:
rows, cols = cars_df.shape
print("Rows: ", rows)
print("Columns: ", cols)

Rows:  161
Columns:  11

In [92]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

### EDA - Exploratory Data Analysis 
- Data profiling
    - Structure (shape)
    - Quality (missing value, duplicates, unique values)
    - Content (data types, dispersion, measure central tendency)
- Profiling Techniques
    - Data Type and format validation
    - Statistical summaries(descriptive stats, values counts, frequently checks)
    - Uniqueness and cardinality
    - Pattern recognition
    - Cross validation

In [93]:
cars_df.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [94]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}
tech_df = pd.DataFrame(tech)

In [96]:
tech_df = tech_df.rename(columns ={'Courses': 'Course Name'})

In [98]:
tech_df.head()

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year